
development:
  adapter: mysql2
  database: tutorial_development
  username: testuser
  password: Password1
  encoding: utf8
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  database: tutorial_test
  username: testuser
  password: Password1
  encoding: utf8
  host: 127.0.0.1
  port: 3306
